
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znymtaxntdenjoehoinu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpueW10YXhudGRlbmpvZWhvaW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjIzMzYsImV4cCI6MjA2MTIzODMzNn0.sENLE0QL9jMerYetaxOB5Iyh1xGzSQuVnIXF4LfMt7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Function to check if Supabase connection is working
export const checkSupabaseConnection = async () => {
  try {
    // Try a simple query to verify connection
    const { data, error } = await supabase.from('users').select('id').limit(1);
    
    if (error) {
      return { connected: false, error: error.message };
    }
    
    return { connected: true };
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : 'Unknown error';
    return { connected: false, error: errorMessage };
  }
};
